AWSTemplateFormatVersion: '2010-09-09'
Description: Create IAM Roles for EFS mounting and ECS task execution

Resources:

  # IAM role for ECS task execution (used for mounting EFS to the container)
  tm-devops-trainee-ecs-task-execution-role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: tm-devops-trainee-ecs-task-execution-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: [ecs-tasks.amazonaws.com]
            Action: ['sts:AssumeRole']
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Policies:
        - PolicyName: tm-devops-trainee-EFSAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - elasticfilesystem:ClientMount
                  - elasticfilesystem:ClientWrite
                  - elasticfilesystem:DescribeMountTargets
                  - elasticfilesystem:DescribeFileSystems
                Resource: !ImportValue tm-devops-trainee-efs-arn

  # IAM role for ECS tasks (allows ECS tasks to interact with AWS systems manager for exec access)
  tm-devops-trainee-ecs-task-role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: tm-devops-trainee-ecs-task-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: [ecs-tasks.amazonaws.com]
            Action: ['sts:AssumeRole']
      Policies:
        - PolicyName: tm-devops-trainee-ExecAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ssmmessages:CreateControlChannel
                  - ssmmessages:CreateDataChannel
                  - ssmmessages:OpenControlChannel
                  - ssmmessages:OpenDataChannel
                Resource: '*'

Outputs:

  # Export IAM role ARNs for ECS tasks
  TaskExecutionRoleArn:
    Description: ECS Task Execution Role ARN
    Value: !GetAtt tm-devops-trainee-ecs-task-execution-role.Arn
    Export:
      Name: 'tm-devops-trainee-task-execution-role-arn'

  TaskRoleArn:
    Description: ECS Task Role ARN
    Value: !GetAtt tm-devops-trainee-ecs-task-role.Arn
    Export:
      Name: 'tm-devops-trainee-task-role-arn'



